// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package transport

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerDataEvent struct {
	_       structs.HostLayout
	Fd      uint32
	Size    uint32
	Payload [4096]uint8
}

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	TraceReadEnter *ebpf.ProgramSpec `ebpf:"trace_read_enter"`
	TraceReadExit  *ebpf.ProgramSpec `ebpf:"trace_read_exit"`
	TraceWrite     *ebpf.ProgramSpec `ebpf:"trace_write"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	ConfigPid   *ebpf.MapSpec `ebpf:"config_pid"`
	EventBufMap *ebpf.MapSpec `ebpf:"event_buf_map"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	ReadArgs    *ebpf.MapSpec `ebpf:"read_args"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	ConfigPid   *ebpf.Map `ebpf:"config_pid"`
	EventBufMap *ebpf.Map `ebpf:"event_buf_map"`
	Events      *ebpf.Map `ebpf:"events"`
	ReadArgs    *ebpf.Map `ebpf:"read_args"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.ConfigPid,
		m.EventBufMap,
		m.Events,
		m.ReadArgs,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	TraceReadEnter *ebpf.Program `ebpf:"trace_read_enter"`
	TraceReadExit  *ebpf.Program `ebpf:"trace_read_exit"`
	TraceWrite     *ebpf.Program `ebpf:"trace_write"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.TraceReadEnter,
		p.TraceReadExit,
		p.TraceWrite,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_bpfel.o
var _TracerBytes []byte
